export const SNAP = 8;
export const SAVE_DEBOUNCE = 650;

export const FONT_LIST = [
  { k: 'system', n: 'Sistema', css: 'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial' },
  { k: 'inter', n: 'Inter', css: 'Inter, ui-sans-serif, system-ui' },
  { k: 'poppins', n: 'Poppins', css: 'Poppins, ui-sans-serif' },
  { k: 'montserrat', n: 'Montserrat', css: 'Montserrat, ui-sans-serif' },
  { k: 'roboto', n: 'Roboto', css: 'Roboto, ui-sans-serif' },
  { k: 'opensans', n: 'Open Sans', css: '"Open Sans", ui-sans-serif' },
  { k: 'lato', n: 'Lato', css: 'Lato, ui-sans-serif' },
  { k: 'nunito', n: 'Nunito', css: 'Nunito, ui-sans-serif' },
  { k: 'raleway', n: 'Raleway', css: 'Raleway, ui-sans-serif' },
  { k: 'worksans', n: 'Work Sans', css: '"Work Sans", ui-sans-serif' },
  { k: 'dmsans', n: 'DM Sans', css: '"DM Sans", ui-sans-serif' },
  { k: 'manrope', n: 'Manrope', css: 'Manrope, ui-sans-serif' },
  { k: 'sourcesans', n: 'Source Sans 3', css: '"Source Sans 3", ui-sans-serif' },
  { k: 'mulish', n: 'Mulish', css: 'Mulish, ui-sans-serif' },
  { k: 'rubik', n: 'Rubik', css: 'Rubik, ui-sans-serif' },
  { k: 'merriweather', n: 'Merriweather', css: 'Merriweather, ui-serif, Georgia' },
  { k: 'playfair', n: 'Playfair Display', css: '"Playfair Display", ui-serif, Georgia' },
  { k: 'ptserif', n: 'PT Serif', css: '"PT Serif", ui-serif, Georgia' },
  { k: 'jetbrains', n: 'JetBrains Mono', css: '"JetBrains Mono", ui-monospace' },
  { k: 'firacode', n: 'Fira Code', css: '"Fira Code", ui-monospace' },
];

export const SIZE_LIST = [6,7,8,9,10,11,12,14,16,18,20,22,24,26,28,32,36,40,44,48,54,60,66,72];

export const PRESETS_MM = {
  a4: { w: 210, h: 297 },
  a3: { w: 297, h: 420 },
  letter: { w: 216, h: 279 },
  legal: { w: 216, h: 356 },
};

export const DEFAULT_PAGE_STATE = {
  preset: 'a4',
  ori: 'portrait',
  unit: 'mm',
  w: 210,
  h: 297,
  margins: { top: 20, right: 20, bottom: 20, left: 20 },
  bg: {
    type: 'gradient',
    c1: '#c8f7ff',
    c2: '#f7d6ff',
    dir: '45deg',
    mosaic: 'dots',
  },
};

export const BLOCK_DEFAULTS = {
  title: {
    kind: 'title',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Título',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 28,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  text: {
    kind: 'text',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Escribe un texto aquí…',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  divider: {
    kind: 'divider',
    variant: null,
    w: 520,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_text: {
    kind: 'q_text',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Pregunta',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_radio: {
    kind: 'q_radio',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Pregunta de opción múltiple',
      align: 'left',
      required: false,
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_check: {
    kind: 'q_check',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Checkbox múltiple',
      align: 'left',
      required: false,
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
    q_select: {
    kind: 'q_select',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Combo box',
      align: 'left',
      required: false,
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_scale: {
    kind: 'q_scale',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Escala 1–5',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_date: {
    kind: 'q_date',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Fecha',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  img: {
    kind: 'img',
    variant: null,
    w: 420,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
};