export const SNAP = 8;
export const SAVE_DEBOUNCE = 650;

export const FONT_LIST = [
  { k: 'system', n: 'Sistema', css: 'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial' },
  { k: 'inter', n: 'Inter', css: 'Inter, ui-sans-serif, system-ui' },
  { k: 'poppins', n: 'Poppins', css: 'Poppins, ui-sans-serif' },
  { k: 'montserrat', n: 'Montserrat', css: 'Montserrat, ui-sans-serif' },
  { k: 'roboto', n: 'Roboto', css: 'Roboto, ui-sans-serif' },
  { k: 'opensans', n: 'Open Sans', css: '"Open Sans", ui-sans-serif' },
  { k: 'lato', n: 'Lato', css: 'Lato, ui-sans-serif' },
  { k: 'nunito', n: 'Nunito', css: 'Nunito, ui-sans-serif' },
  { k: 'raleway', n: 'Raleway', css: 'Raleway, ui-sans-serif' },
  { k: 'worksans', n: 'Work Sans', css: '"Work Sans", ui-sans-serif' },
  { k: 'dmsans', n: 'DM Sans', css: '"DM Sans", ui-sans-serif' },
  { k: 'manrope', n: 'Manrope', css: 'Manrope, ui-sans-serif' },
  { k: 'sourcesans', n: 'Source Sans 3', css: '"Source Sans 3", ui-sans-serif' },
  { k: 'mulish', n: 'Mulish', css: 'Mulish, ui-sans-serif' },
  { k: 'rubik', n: 'Rubik', css: 'Rubik, ui-sans-serif' },
  { k: 'merriweather', n: 'Merriweather', css: 'Merriweather, ui-serif, Georgia' },
  { k: 'playfair', n: 'Playfair Display', css: '"Playfair Display", ui-serif, Georgia' },
  { k: 'ptserif', n: 'PT Serif', css: '"PT Serif", ui-serif, Georgia' },
  { k: 'jetbrains', n: 'JetBrains Mono', css: '"JetBrains Mono", ui-monospace' },
  { k: 'firacode', n: 'Fira Code', css: '"Fira Code", ui-monospace' },
];

export const SIZE_LIST = [6,7,8,9,10,11,12,14,16,18,20,22,24,26,28,32,36,40,44,48,54,60,66,72];

export const PRESETS_MM = {
  a4: { w: 210, h: 297 },
  a3: { w: 297, h: 420 },
  letter: { w: 216, h: 279 },
  legal: { w: 216, h: 356 },
};

export const DEFAULT_PAGE_STATE = {
  preset: 'a4',
  ori: 'portrait',
  unit: 'mm',
  w: 210,
  h: 297,
  margins: { top: 20, right: 20, bottom: 20, left: 20 },
  bg: {
    type: 'gradient',
    c1: '#c8f7ff',
    c2: '#f7d6ff',
    dir: '45deg',
    mosaic: 'dots',
  },
};

export const BLOCK_DEFAULTS = {
  title: {
    kind: 'title',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Título',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 28,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  text: {
    kind: 'text',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Escribe un texto aquí…',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  divider: {
    kind: 'divider',
    variant: 'simple',
    w: 520,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      dividerVariant: 'simple',
      dividerColor: '#e2e8f0',
      dividerThickness: 2,
    },
  },
  divider_double: {
    kind: 'divider',
    variant: 'double',
    w: 520,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      dividerVariant: 'double',
      dividerColor: '#e2e8f0',
      dividerThickness: 2,
    },
  },
  divider_dashed: {
    kind: 'divider',
    variant: 'dashed',
    w: 520,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      dividerVariant: 'dashed',
      dividerColor: '#94a3b8',
      dividerThickness: 2,
    },
  },
  divider_gradient: {
    kind: 'divider',
    variant: 'gradient',
    w: 520,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      dividerVariant: 'gradient',
      dividerColor: '#6366f1',
      dividerThickness: 3,
    },
  },
  divider_text: {
    kind: 'divider',
    variant: 'text',
    w: 520,
    h: null,
    props: {
      html: 'Sección',
      align: 'center',
      required: false,
      options: null,
      font: 'system',
      fontSize: 13,
      color: '#64748b',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      dividerVariant: 'text',
      dividerColor: '#e2e8f0',
      dividerThickness: 1,
    },
  },
  divider_dots: {
    kind: 'divider',
    variant: 'dots',
    w: 520,
    h: null,
    props: {
      html: null,
      align: 'center',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#94a3b8',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      dividerVariant: 'dots',
      dividerColor: '#94a3b8',
      dividerThickness: 2,
    },
  },
  highlight_box: {
    kind: 'highlight_box',
    variant: null,
    w: 420,
    h: null,
    props: {
      html: 'Texto destacado aquí',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#1e40af',
      bg: '#eff6ff',
      alpha: 100,
      optColor: '',
      img: null,
      boxVariant: 'info',
      borderColor: '#3b82f6',
    },
  },
  highlight_success: {
    kind: 'highlight_box',
    variant: 'success',
    w: 420,
    h: null,
    props: {
      html: 'Mensaje de éxito o confirmación',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#166534',
      bg: '#f0fdf4',
      alpha: 100,
      optColor: '',
      img: null,
      boxVariant: 'success',
      borderColor: '#22c55e',
    },
  },
  highlight_warning: {
    kind: 'highlight_box',
    variant: 'warning',
    w: 420,
    h: null,
    props: {
      html: 'Nota importante o advertencia',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#92400e',
      bg: '#fffbeb',
      alpha: 100,
      optColor: '',
      img: null,
      boxVariant: 'warning',
      borderColor: '#f59e0b',
    },
  },
  highlight_danger: {
    kind: 'highlight_box',
    variant: 'danger',
    w: 420,
    h: null,
    props: {
      html: 'Atención: información crítica',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#991b1b',
      bg: '#fef2f2',
      alpha: 100,
      optColor: '',
      img: null,
      boxVariant: 'danger',
      borderColor: '#ef4444',
    },
  },
  quote: {
    kind: 'quote',
    variant: null,
    w: 420,
    h: null,
    props: {
      html: 'Escribe aquí tu cita o texto destacado.',
      align: 'left',
      required: false,
      options: null,
      font: 'merriweather',
      fontSize: 16,
      color: '#334155',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      quoteColor: '#6366f1',
    },
  },
  badge: {
    kind: 'badge',
    variant: null,
    w: 200,
    h: null,
    props: {
      html: 'Etiqueta',
      align: 'center',
      required: false,
      options: null,
      font: 'system',
      fontSize: 13,
      color: '#4f46e5',
      bg: '#eef2ff',
      alpha: 100,
      optColor: '',
      img: null,
      badgeVariant: 'pill',
      borderColor: '#c7d2fe',
    },
  },
  badge_solid: {
    kind: 'badge',
    variant: 'solid',
    w: 200,
    h: null,
    props: {
      html: 'Etiqueta',
      align: 'center',
      required: false,
      options: null,
      font: 'system',
      fontSize: 13,
      color: '#ffffff',
      bg: '#6366f1',
      alpha: 100,
      optColor: '',
      img: null,
      badgeVariant: 'solid',
      borderColor: '#6366f1',
    },
  },
  callout: {
    kind: 'callout',
    variant: null,
    w: 420,
    h: null,
    props: {
      html: 'Escribe aquí el contenido del callout.',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#1e293b',
      bg: '#f8fafc',
      alpha: 100,
      optColor: '',
      img: null,
      calloutIcon: '💡',
      calloutTitle: 'Nota',
      borderColor: '#6366f1',
    },
  },
  callout_tip: {
    kind: 'callout',
    variant: 'tip',
    w: 420,
    h: null,
    props: {
      html: 'Consejo útil para el encuestado.',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '#1e293b',
      bg: '#f0fdf4',
      alpha: 100,
      optColor: '',
      img: null,
      calloutIcon: '✅',
      calloutTitle: 'Consejo',
      borderColor: '#22c55e',
    },
  },
  number_heading: {
    kind: 'number_heading',
    variant: null,
    w: 420,
    h: null,
    props: {
      html: 'Título de sección',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 18,
      color: '#0f172a',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      sectionNumber: '01',
      numberColor: '#6366f1',
    },
  },
  q_text: {
    kind: 'q_text',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Pregunta',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_radio: {
    kind: 'q_radio',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Pregunta de opción múltiple',
      align: 'left',
      required: false,
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_check: {
    kind: 'q_check',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Checkbox múltiple',
      align: 'left',
      required: false,
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
    q_select: {
    kind: 'q_select',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Combo box',
      align: 'left',
      required: false,
      options: ['Opción 1', 'Opción 2', 'Opción 3'],
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_scale: {
    kind: 'q_scale',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Escala 1–5',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_date: {
    kind: 'q_date',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Fecha',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_yesno: {
    kind: 'q_yesno',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: '¿Estás de acuerdo?',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
  q_stars: {
    kind: 'q_stars',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Califica tu experiencia',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      stars: 5,
    },
  },
  q_numeric: {
    kind: 'q_numeric',
    variant: null,
    w: 360,
    h: null,
    props: {
      html: 'Del 1 al 10',
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
      min: 1,
      max: 10,
    },
  },
  img: {
    kind: 'img',
    variant: null,
    w: 420,
    h: null,
    props: {
      html: null,
      align: 'left',
      required: false,
      options: null,
      font: 'system',
      fontSize: 14,
      color: '',
      bg: '',
      alpha: 100,
      optColor: '',
      img: null,
    },
  },
};